/* Market Intel Agent Frontend (app.js)
   - Live: NewsAPI (/api/news), Google Trends via pytrends (/api/trends)
   - AI: OpenAI (/api/analyze)
*/

// -- Constants ----------------------------------------------------------------
const QUICK_TAGS = [
  "portable tech",
  "home espresso machines",
  "sneakers",
  "wireless earbuds",
  "skincare",
  "electric bikes",
  "smart home",
  "energy drinks",
];

const LOADING_STEPS = [
  "Fetching live news coverage...",
  "Pulling Google Trends interest...",
  "Computing trend velocity...",
  "Analyzing price history...",
  "Running AI forecast model...",
  "Building your report...",
];

const HISTORY_WEEKS = 104;
const TRENDS_LOOKBACK_DAYS = HISTORY_WEEKS * 7;

// Keep these in sync with how your backend is actually implemented
const DATA_SOURCES = [
  {
    name: "NewsAPI.org",
    type: "Live News Coverage Data",
    desc: "Real-time news article data pulled from NewsAPI.org. Article counts are fetched live at report time and converted into a 0100 coverage score based on recent volume (up to 30 days).",
    tag: "live",
  },
  {
    name: "Google Trends (pytrends)",
    type: "Search Interest Data",
    desc: "Live Google Trends interest is fetched via pytrends for the same 104-week historical window used in the pricing graph.",
    tag: "live",
  },
  {
    name: "eBay Buy Browse API",
    type: "Live Retail & Marketplace Pricing",
    desc: "Sold/completed prices are pulled from eBay when available to estimate clearing price. If sold data is unavailable, pricing falls back to active listings or AI estimates.",
    tag: "live",
  },
  {
    name: "WTO Timeseries API",
    type: "Trade & Tariff Data",
    desc: "Tariff context is fetched from WTO using inferred or explicit trading partners, with compact fallback logic when partner-HS data is sparse.",
    tag: "live",
  },
  {
    name: "OpenAI Model",
    type: "AI Analysis & Synthesis Engine",
    desc: "Trend narratives, forecasts, keyword signals, and non-live scores are generated by OpenAI. These are informed estimates, not real-time measurements.",
    tag: "ai",
  },
];

// -- State --------------------------------------------------------------------
let report = null;
let newsData = null;
let trendsData = null;
let ebayMapData = null;
let wtoData = null;
let loadInterval = null;
let stateMapRenderToken = 0;
let followupMessages = [];

const STATE_ABBR_TO_FIPS = {
  AL: "01", AK: "02", AZ: "04", AR: "05", CA: "06", CO: "08", CT: "09", DE: "10", DC: "11",
  FL: "12", GA: "13", HI: "15", ID: "16", IL: "17", IN: "18", IA: "19", KS: "20", KY: "21",
  LA: "22", ME: "23", MD: "24", MA: "25", MI: "26", MN: "27", MS: "28", MO: "29", MT: "30",
  NE: "31", NV: "32", NH: "33", NJ: "34", NM: "35", NY: "36", NC: "37", ND: "38", OH: "39",
  OK: "40", OR: "41", PA: "42", RI: "44", SC: "45", SD: "46", TN: "47", TX: "48", UT: "49",
  VT: "50", VA: "51", WA: "53", WV: "54", WI: "55", WY: "56",
};
const FIPS_TO_STATE_ABBR = Object.fromEntries(Object.entries(STATE_ABBR_TO_FIPS).map(([k, v]) => [v, k]));

// -- Helpers ------------------------------------------------------------------
const $ = (id) => document.getElementById(id);
const esc = (s) =>
  s == null
    ? ""
    : String(s)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");

function badgeClass(b = "") {
  const u = b.toUpperCase();
  if (u.includes("RISING")) return "rising";
  if (u.includes("PEAKED") || u.includes("PLATEAU")) return "peaked";
  if (u.includes("DECLINING")) return "declining";
  if (u.includes("EMERGING")) return "emerging";
  return "steady";
}
function badgeIcon(b = "") {
  const u = b.toUpperCase();
  if (u.includes("RISING")) return "UP";
  if (u.includes("PEAKED")) return "TOP";
  if (u.includes("DECLINING")) return "DOWN";
  if (u.includes("EMERGING")) return "NEW";
  return "-";
}
function signalColor(s) {
  return s >= 70 ? "green" : s >= 40 ? "blue" : "amber";
}
function hasNumber(x) {
  return typeof x === "number" && Number.isFinite(x);
}

function renderArimaRobustnessCard(ar) {
  if (!ar || typeof ar !== "object") return "";
  const adfText = hasNumber(ar.adfPValue) ? Number(ar.adfPValue).toFixed(4) : "n/a";
  const lbText = hasNumber(ar.ljungBoxPValue) ? Number(ar.ljungBoxPValue).toFixed(4) : "n/a";
  const rmseText = hasNumber(ar.holdoutRMSE) ? Number(ar.holdoutRMSE).toFixed(2) : "n/a";
  const naiveText = hasNumber(ar.naiveRMSE) ? Number(ar.naiveRMSE).toFixed(2) : "n/a";
  const meanText = hasNumber(ar.rollingMeanRMSE) ? Number(ar.rollingMeanRMSE).toFixed(2) : "n/a";
  const clippedNote = ar.clippedUpper
    ? `Forecast ceiling note: unconstrained ARIMA average is ${esc(
        hasNumber(ar.unclippedFutureScore) ? Number(ar.unclippedFutureScore).toFixed(2) : "n/a"
      )}, so the displayed forecast is capped at Google Trends' 100 upper bound.`
    : "";
  return `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">ARIMA Robustness <span class="ai-badge" style="font-size:9px">model evidence</span></div>
    <div class="arima-grid" style="margin-bottom:14px">
      <div class="stat-card arima-stat-card">
        <div class="stat-label">Specification</div>
        <div class="arima-stat-value purple">${esc(ar.modelOrder || "ARIMA")}</div>
        <div class="arima-stat-sub">Difference order ${esc(ar.differenceOrder || 1)}</div>
        <div class="arima-stat-sub">Train ${esc(ar.trainingPoints || "n/a")} | Holdout ${esc(ar.holdoutPoints || "n/a")}</div>
      </div>
      <div class="stat-card arima-stat-card">
        <div class="stat-label">Holdout RMSE</div>
        <div class="arima-stat-value blue">${esc(rmseText)}</div>
        <div class="arima-stat-sub">Naive baseline ${esc(naiveText)}</div>
        <div class="arima-stat-sub">Rolling mean baseline ${esc(meanText)}</div>
      </div>
      <div class="stat-card arima-stat-card">
        <div class="stat-label">Stationarity</div>
        <div class="arima-stat-value ${hasNumber(ar.adfPValue) && Number(ar.adfPValue) < 0.05 ? "green" : "amber"}">ADF p=${esc(adfText)}</div>
        <div class="arima-stat-sub">Lower than 0.05 suggests the differenced series is stationary.</div>
      </div>
      <div class="stat-card arima-stat-card">
        <div class="stat-label">Residual Check</div>
        <div class="arima-stat-value ${hasNumber(ar.ljungBoxPValue) && Number(ar.ljungBoxPValue) > 0.05 ? "green" : "amber"}">LB p=${esc(lbText)}</div>
        <div class="arima-stat-sub">Higher than 0.05 suggests residual autocorrelation is limited.</div>
        <div class="arima-stat-sub">AIC ${esc(ar.aic ?? "n/a")} | BIC ${esc(ar.bic ?? "n/a")}</div>
      </div>
    </div>
    <div class="stat-sub">Benchmark comparison: ARIMA ${ar.beatsNaive ? "beats" : "does not beat"} naive carry-forward and ${ar.beatsRollingMean ? "beats" : "does not beat"} rolling-mean on the holdout window.</div>
    ${clippedNote ? `<div class="stat-sub" style="margin-top:8px">${clippedNote}</div>` : ""}
  </div>`;
}

function explainWtoIndicator(w) {
  const code = String(w?.indicator || "").toUpperCase();
  const hsCategory = String(w?.usedHsCategory || w?.hsCategory || "").trim();
  const hsCode = String(
    (w?.usedHsCode && w?.usedHsCode !== "default" ? w?.usedHsCode : w?.hsCode) || ""
  ).trim();
  const hsSuffix = hsCategory
    ? ` HS category: ${hsCategory}${hsCode ? ` (HS ${hsCode})` : ""}.`
    : "";
  if (code === "HS_A_0010") {
    return `U.S. MFN tariff for the selected HS product code (not country-specific).${hsSuffix}`;
  }
  if (code === "TP_A_0010") {
    return `U.S. MFN all-products average tariff (broad fallback).${hsSuffix}`;
  }
  if (code === "HS_P_0070") {
    return `Partner-specific preferential tariff at HS level (sparse coverage).${hsSuffix}`;
  }
  return `${String(w?.indicatorLabel || "WTO tariff indicator")}.${hsSuffix}`;
}

function humanizeToolName(name = "") {
  return String(name || "")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function cleanPresentationText(value = "") {
  return String(value || "")
    .replace(/\u00a0/g, " ")
    .replace(/Â/g, "")
    .replace(/â€™/g, "'")
    .replace(/â€œ/g, '"')
    .replace(/â€/g, '"')
    .replace(/â€”/g, "-")
    .replace(/â€“/g, "-")
    .replace(/\s+/g, " ")
    .trim();
}

function formatConfidenceLabel(value = "") {
  const v = cleanPresentationText(value).toLowerCase();
  if (!v) return "Confidence not recorded";
  return v.charAt(0).toUpperCase() + v.slice(1) + " confidence";
}

function summarizeAgentRun(run) {
  if (!run || typeof run !== "object") return "";
  const tool = String(run.tool || "");
  const summary = cleanPresentationText(run.summary || "");
  if (!summary) return "";

  if (tool === "news") {
    const score = summary.match(/score=(\d+)/i)?.[1];
    const total = summary.match(/totalResults=(\d+)/i)?.[1];
    const titlesBlock = summary.match(/topTitles=\[(.*)\]/i)?.[1] || "";
    const titles = titlesBlock
      .split(/',\s*'|",\s*"/)
      .map((s) => cleanPresentationText(s.replace(/^['"]|['"]$/g, "")))
      .filter(Boolean)
      .slice(0, 2);
    let text = "";
    if (score) text += `Coverage scored ${score}/100`;
    if (total) text += `${text ? " from " : ""}${total} recent articles`;
    if (titles.length) text += `${text ? ". " : ""}Most visible topics: ${titles.join("; ")}.`;
    return text || summary;
  }

  if (tool === "trends") {
    const score = summary.match(/score=(\d+)/i)?.[1];
    const recentRaw = summary.match(/recentPoints=\[(.*)\]/i)?.[1] || "";
    const values = Array.from(recentRaw.matchAll(/value['"]?:\s*(\d+)/g)).map((m) => Number(m[1]));
    const latest = values.length ? values[values.length - 1] : null;
    const prev = values.length > 1 ? values[values.length - 2] : null;
    const trendText =
      latest != null && prev != null
        ? latest > prev
          ? "Momentum is still rising."
          : latest < prev
          ? "Momentum cooled slightly in the latest reading."
          : "Momentum held steady in the latest reading."
        : "";
    return `${score ? `Search interest scored ${score}/100.` : ""} ${trendText}`.trim() || summary;
  }

  if (tool === "ebay_pricing") {
    const avg = summary.match(/avg=([\d.]+)/i)?.[1];
    const low = summary.match(/range=\(([\d.]+),/i)?.[1];
    const high = summary.match(/range=\([\d.]+,\s*([\d.]+)\)/i)?.[1];
    const sample = summary.match(/sample=(\d+)/i)?.[1];
    return `Observed market pricing averaged $${avg || "n/a"}${low && high ? ` with a typical range of $${low}-$${high}` : ""}${sample ? ` across ${sample} listings` : ""}.`;
  }

  if (tool === "pricing_history") {
    const count = summary.match(/weeklyPoints=(\d+)/i)?.[1];
    return `${count ? `${count} recent weekly pricing observations were available` : "Recent pricing history was available"} to check continuity and direction over time.`;
  }

  if (tool === "wto_trade") {
    const headline = summary.match(/headline=([^[]*?)(?:warnings=|$)/i)?.[1];
    return cleanPresentationText(headline || summary);
  }

  if (tool === "ebay_map") {
    const count = summary.match(/count=(\d+)/i)?.[1];
    return `${count ? `${count} regional pricing clusters were mapped` : "Regional pricing patterns were mapped"} to identify geographic variation.`;
  }

  return summary;
}

function renderAgentTraceCard(agentTrace) {
  if (!agentTrace || typeof agentTrace !== "object") return "";
  const toolPlan = Array.isArray(agentTrace.toolPlan) ? agentTrace.toolPlan : [];
  const additionalTools = Array.isArray(agentTrace.additionalTools) ? agentTrace.additionalTools : [];
  const toolRuns = Array.isArray(agentTrace.toolRuns) ? agentTrace.toolRuns : [];
  const warnings = Array.isArray(agentTrace.warnings) ? agentTrace.warnings : [];
  const reflection = agentTrace.reflection || {};

  return `<div class="section-card agent-card" style="margin-bottom:20px">
    <div class="section-heading">Agent Workflow <span class="live-badge" style="font-size:9px">plan-act-observe</span></div>
    <div class="agent-steps">
      <span class="agent-step">1. Planned</span>
      <span class="agent-step">2. Gathered Evidence</span>
      <span class="agent-step">3. Reflected</span>
    </div>
    <div class="agent-grid">
      <div class="agent-panel">
        <div class="agent-label">Objective</div>
        <div class="agent-text">${esc(cleanPresentationText(agentTrace.objective || "No objective recorded."))}</div>
      </div>
      <div class="agent-panel">
        <div class="agent-label">Why These Tools</div>
        <div class="agent-text">${esc(cleanPresentationText(agentTrace.planReasoning || "No planner notes recorded."))}</div>
      </div>
      <div class="agent-panel">
        <div class="agent-label">Selected Tools</div>
        <div class="agent-chip-row">${
          toolPlan.length
            ? toolPlan.map((tool) => `<span class="agent-chip">${esc(humanizeToolName(tool))}</span>`).join("")
            : `<span class="agent-empty">No tools recorded.</span>`
        }</div>
      </div>
      <div class="agent-panel">
        <div class="agent-label">Decision Summary</div>
        <div class="agent-text">${esc(formatConfidenceLabel(reflection.confidence || ""))}</div>
        <div class="agent-sub">${esc(cleanPresentationText(reflection.stopReason || "No reflection summary recorded."))}</div>
        ${
          additionalTools.length
            ? `<div class="agent-sub" style="margin-top:8px">Additional evidence gathered: ${esc(
                additionalTools.map(humanizeToolName).join(", ")
              )}</div>`
            : `<div class="agent-sub" style="margin-top:8px">Additional evidence gathered: none needed</div>`
        }
      </div>
    </div>
    ${
      agentTrace.clarificationRequested && agentTrace.clarifyingQuestion
        ? `<div class="agent-note">Clarification considered: ${esc(cleanPresentationText(agentTrace.clarifyingQuestion))}</div>`
        : ""
    }
    ${
      toolRuns.length
        ? `<div class="agent-runs-label">Evidence Collected</div><div class="agent-runs">${toolRuns
            .map(
              (run) => `<div class="agent-run">
                <div class="agent-run-head">
                  <span class="agent-run-name">${esc(humanizeToolName(run.tool || ""))}</span>
                  <span class="agent-run-status ${run.status === "error" ? "error" : "ok"}">${esc(
                    run.status === "error" ? "issue" : "used"
                  )}</span>
                </div>
                <div class="agent-run-summary">${esc(summarizeAgentRun(run))}</div>
              </div>`
            )
            .join("")}</div>`
        : ""
    }
    ${
      warnings.length
        ? `<div class="agent-note warning">Warnings: ${esc(warnings.join(" | "))}</div>`
        : ""
    }
  </div>`;
}

function renderAgentTraceMini(agentTrace) {
  if (!agentTrace || typeof agentTrace !== "object") return "";
  const toolPlan = Array.isArray(agentTrace.toolPlan) ? agentTrace.toolPlan : [];
  const additionalTools = Array.isArray(agentTrace.additionalTools) ? agentTrace.additionalTools : [];
  return `<div class="followup-trace">
    <div class="followup-trace-title">Workflow summary</div>
    <div class="followup-trace-text">${esc(cleanPresentationText(agentTrace.objective || "Follow-up evidence gathering"))}</div>
    <div class="followup-trace-text">Tools: ${esc(
      toolPlan.length ? toolPlan.map(humanizeToolName).join(", ") : "none recorded"
    )}</div>
    <div class="followup-trace-text">Additional evidence: ${esc(
      additionalTools.length ? additionalTools.map(humanizeToolName).join(", ") : "none"
    )}</div>
  </div>`;
}

// -- Init ---------------------------------------------------------------------
document.addEventListener("DOMContentLoaded", () => {
  const year = new Date().getFullYear();
  $("header-year").textContent = `Market Intelligence - ${year}`;

  const tagsEl = $("quick-tags");
  QUICK_TAGS.forEach((t) => {
    const btn = document.createElement("button");
    btn.className = "quick-tag";
    btn.textContent = t;
    btn.onclick = () => {
      $("search-input").value = t;
      runAgent(t);
    };
    tagsEl.appendChild(btn);
  });

  $("search-input").addEventListener("keydown", (e) => {
    if (e.key === "Enter") runAgent($("search-input").value);
  });
  $("run-btn").addEventListener("click", () =>
    runAgent($("search-input").value)
  );
});

// -- Loading UI ---------------------------------------------------------------
function showLoading() {
  $("loading-section").classList.remove("hidden");
  $("error-section").classList.add("hidden");
  $("results-section").classList.add("hidden");
  $("run-btn").disabled = true;

  const list = $("loading-steps");
  list.innerHTML = "";
  LOADING_STEPS.forEach((s, i) => {
    const div = document.createElement("div");
    div.className = "loading-step-item" + (i === 0 ? " active" : "");
    div.style.animationDelay = `${i * 0.08}s`;
    div.textContent = (i === 0 ? "\u23F3 " : "  ") + s;
    div.id = `lstep-${i}`;
    list.appendChild(div);
  });

  let step = 0;
  loadInterval = setInterval(() => {
    step++;
    LOADING_STEPS.forEach((_, i) => {
      const el = $(`lstep-${i}`);
      if (!el) return;
      el.className =
        "loading-step-item " +
        (i < step ? "done" : i === step ? "active" : "");
      el.textContent =
        (i < step ? "\u2705 " : i === step ? "\u23F3 " : "  ") + LOADING_STEPS[i];
    });
    if (step >= LOADING_STEPS.length - 1) clearInterval(loadInterval);
  }, 1200);
}

function hideLoading() {
  clearInterval(loadInterval);
  $("loading-section").classList.add("hidden");
  $("run-btn").disabled = false;
}

// -- Main agent ---------------------------------------------------------------
async function runAgent(category) {
  const q = (category || "").trim();
  if (!q) return;

  showLoading();
  report = null;
  newsData = null;
  trendsData = null;
  ebayMapData = null;
  wtoData = null;
  followupMessages = [];

  try {
    const [newsResp, trendsResp, mapResp, wtoResp, aiResp] = await Promise.allSettled([
      fetch(`/api/news?q=${encodeURIComponent(q)}`).then((r) => {
        if (!r.ok) throw new Error("News fetch failed");
        return r.json();
      }),
      fetch(`/api/trends?q=${encodeURIComponent(q)}&days=${TRENDS_LOOKBACK_DAYS}`).then((r) => {
        if (!r.ok) throw new Error("Trends fetch failed");
        return r.json();
      }),
      fetch(`/api/pricing/map?q=${encodeURIComponent(q)}&limit=1000`).then((r) => {
        if (!r.ok) throw new Error("eBay map fetch failed");
        return r.json();
      }),
      fetch(`/api/wto/trade?q=${encodeURIComponent(q)}&years=5&strict_targeted=true`).then((r) => {
        if (!r.ok) throw new Error("WTO fetch failed");
        return r.json();
      }),
      fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ category: q }),
      }).then((r) => {
        if (!r.ok)
          return r.json().then((d) => {
            throw new Error(d.detail || "AI error");
          });
        return r.json();
      }),
    ]);

    if (aiResp.status === "rejected") {
      throw new Error("AI report failed: " + (aiResp.reason?.message || ""));
    }

    report = aiResp.value;

    newsData = newsResp.status === "fulfilled" ? newsResp.value : null;
    trendsData = trendsResp.status === "fulfilled" ? trendsResp.value : null;
    ebayMapData = mapResp.status === "fulfilled" ? mapResp.value : null;
    wtoData = wtoResp.status === "fulfilled" ? wtoResp.value : null;

    // Live overrides
    if (newsData && hasNumber(newsData.score)) report.newsScore = newsData.score;
    if (trendsData && Array.isArray(trendsData.points) && trendsData.points.length > 0 && hasNumber(trendsData.score))
      report.googleTrendScore = trendsData.score;

    hideLoading();
    renderResults();
  } catch (err) {
    hideLoading();
    $("error-section").classList.remove("hidden");
    $("error-msg").textContent = err.message || String(err);
  }
}

// -- SVG sparkline builder ----------------------------------------------------
function buildSparklineSVG(monthlyHistory) {
  if (!monthlyHistory || !monthlyHistory.length) return "";
  const W = 600,
    H = 120,
    pad = 10,
    leftPad = 52;
  const prices = monthlyHistory.map((d) => d.price);
  const rawMin = Math.min(...prices),
    rawMax = Math.max(...prices);
  const spread = Math.max(1, rawMax - rawMin);
  // Add vertical headroom so the chart is less truncated/zoomed-in.
  const padAmt = spread * 0.2;
  const mn = Math.max(0, rawMin - padAmt);
  const mx = rawMax + padAmt;
  const rng = mx - mn || 1;
  const x = (i) =>
    leftPad + (i / (monthlyHistory.length - 1)) * (W - leftPad - pad);
  const y = (p) => H - pad - ((p - mn) / rng) * (H - pad * 2);

  const histPts = monthlyHistory.filter((d) => !d.projected);
  const projPts = [
    histPts[histPts.length - 1],
    ...monthlyHistory.filter((d) => d.projected),
  ];

  const toPath = (pts) =>
    pts
      .map((d, i) => {
        const idx = monthlyHistory.indexOf(d);
        return `${i === 0 ? "M" : "L"}${x(idx)},${y(d.price)}`;
      })
      .join(" ");

  const midIdx = Math.floor(monthlyHistory.length / 2);
  const yTop = y(mx);
  const yMid = y((mx + mn) / 2);
  const yBot = y(mn);
  const fmt = (v) => `$${Number(v).toFixed(0)}`;

  return `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
    <rect width="${W}" height="${H}" fill="#f8f7f4" rx="6"/>
    <line x1="${leftPad}" y1="${pad}" x2="${leftPad}" y2="${H - pad}" stroke="#e4e1d8" stroke-width="1"/>
    <line x1="${leftPad}" y1="${yTop}" x2="${W - pad}" y2="${yTop}" stroke="#e4e1d8" stroke-width="1"/>
    <line x1="${leftPad}" y1="${yMid}" x2="${W - pad}" y2="${yMid}" stroke="#ece9e1" stroke-width="1"/>
    <line x1="${leftPad}" y1="${yBot}" x2="${W - pad}" y2="${yBot}" stroke="#e4e1d8" stroke-width="1"/>
    <text x="${leftPad - 6}" y="${yTop + 3}" font-size="9" fill="#8c897e" text-anchor="end">${fmt(
      mx
    )}</text>
    <text x="${leftPad - 6}" y="${yMid + 3}" font-size="9" fill="#8c897e" text-anchor="end">${fmt(
      (mx + mn) / 2
    )}</text>
    <text x="${leftPad - 6}" y="${yBot + 3}" font-size="9" fill="#8c897e" text-anchor="end">${fmt(
      mn
    )}</text>
    <path d="${toPath(histPts)}" fill="none" stroke="#2563eb" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="${toPath(projPts)}" fill="none" stroke="#7c3aed" stroke-width="2" stroke-dasharray="6,4" stroke-linecap="round" stroke-linejoin="round" opacity="0.8"/>
    <text x="${leftPad}" y="${H - 2}" font-size="9" fill="#8c897e">${esc(
      monthlyHistory[0]?.month
    )}</text>
    <text x="${W / 2}" y="${H - 2}" font-size="9" fill="#8c897e" text-anchor="middle">${esc(
      monthlyHistory[midIdx]?.month
    )}</text>
    <text x="${W - pad}" y="${H - 2}" font-size="9" fill="#8c897e" text-anchor="end">${esc(
      monthlyHistory[monthlyHistory.length - 1]?.month
    )}</text>
  </svg>`;
}

function buildTrendsInterestSVG(trendPoints, projectedTarget = null) {
  if (!trendPoints || !trendPoints.length) return "";

  const sorted = [...trendPoints]
    .map((p) => ({
      date: String(p.date || ""),
      value: Number(p.value || 0),
    }))
    .filter((p) => p.date && Number.isFinite(p.value))
    .sort((a, b) => a.date.localeCompare(b.date));
  if (!sorted.length) return "";

  const weekly = [];
  const bucket = new Map();
  sorted.forEach((p) => {
    const d = new Date(`${p.date}T00:00:00`);
    if (Number.isNaN(d.getTime())) return;
    const day = d.getDay();
    const delta = day === 0 ? -6 : 1 - day;
    d.setDate(d.getDate() + delta);
    const wk = d.toISOString().slice(0, 10);
    const arr = bucket.get(wk) || [];
    arr.push(p.value);
    bucket.set(wk, arr);
  });
  [...bucket.keys()].sort().forEach((wk) => {
    const vals = bucket.get(wk) || [];
    const avg = vals.reduce((a, b) => a + b, 0) / Math.max(1, vals.length);
    weekly.push({ week: wk, value: avg });
  });
  if (!weekly.length) return "";

  const W = 600,
    H = 120,
    pad = 10,
    leftPad = 44;
  const x = (i) =>
    leftPad + (i / Math.max(1, weekly.length - 1)) * (W - leftPad - pad);
  const y = (v) => H - pad - (v / 100) * (H - pad * 2);
  const toPath = (pts, startIdx = 0) =>
    pts
      .map((d, i) => {
        const xi = x(startIdx + i);
        return `${i === 0 ? "M" : "L"}${xi},${y(d.value)}`;
      })
      .join(" ");
  const midIdx = Math.floor(weekly.length / 2);

  const projected = [];
  const histLast = weekly[weekly.length - 1]?.value ?? 0;
  const slopeFallback = _simpleSlope(weekly.slice(-8).map((w) => w.value));
  let projTarget = Number(projectedTarget);
  if (!Number.isFinite(projTarget)) {
    projTarget = histLast + slopeFallback * 26;
  }
  projTarget = Math.max(0, Math.min(100, projTarget));
  if (Number.isFinite(projTarget)) {
    const projWeeks = 52;
    for (let i = 1; i <= projWeeks; i++) {
      const t = i / projWeeks;
      projected.push({ value: histLast + (projTarget - histLast) * t });
    }
  }

  // Confidence interval band for projected path.
  // Uses recent weekly volatility and widens over horizon (sqrt time).
  const diffs = [];
  const histForVol = weekly.slice(-52).map((w) => Number(w.value));
  for (let i = 1; i < histForVol.length; i++) {
    const d = histForVol[i] - histForVol[i - 1];
    if (Number.isFinite(d)) diffs.push(d);
  }
  const meanDiff = diffs.length ? diffs.reduce((a, b) => a + b, 0) / diffs.length : 0;
  const varDiff =
    diffs.length > 1
      ? diffs.reduce((a, b) => a + (b - meanDiff) * (b - meanDiff), 0) / (diffs.length - 1)
      : 0;
  const sigma = Math.sqrt(Math.max(0, varDiff));
  const z80 = 1.2816;
  const projUpper = [];
  const projLower = [];
  if (projected.length) {
    for (let i = 0; i < projected.length; i++) {
      const step = i + 1;
      const widening = z80 * sigma * Math.sqrt(step / 4); // mild widening over time
      const center = Number(projected[i].value);
      projUpper.push({ value: Math.max(0, Math.min(100, center + widening)) });
      projLower.push({ value: Math.max(0, Math.min(100, center - widening)) });
    }
  }
  const totalLen = weekly.length + projected.length;
  const xDyn = (i) =>
    leftPad + (i / Math.max(1, totalLen - 1)) * (W - leftPad - pad);
  const toPathDyn = (pts, startIdx = 0) =>
    pts
      .map((d, i) => `${i === 0 ? "M" : "L"}${xDyn(startIdx + i)},${y(d.value)}`)
      .join(" ");
  const toBandPath = (upper, lower, startIdx) => {
    if (!upper.length || !lower.length) return "";
    const up = upper
      .map((d, i) => `${i === 0 ? "M" : "L"}${xDyn(startIdx + i)},${y(d.value)}`)
      .join(" ");
    const lo = [...lower]
      .reverse()
      .map((d, i) => `L${xDyn(startIdx + lower.length - 1 - i)},${y(d.value)}`)
      .join(" ");
    return `${up} ${lo} Z`;
  };

  const projStartX = xDyn(weekly.length - 1);
  const projEndX = xDyn(totalLen - 1);
  const projEndY = y(projTarget);

  return `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
    <rect width="${W}" height="${H}" fill="#f8f7f4" rx="6"/>
    <line x1="${leftPad}" y1="${pad}" x2="${leftPad}" y2="${H - pad}" stroke="#e4e1d8" stroke-width="1"/>
    <line x1="${leftPad}" y1="${y(100)}" x2="${W - pad}" y2="${y(100)}" stroke="#e4e1d8" stroke-width="1"/>
    <line x1="${leftPad}" y1="${y(50)}" x2="${W - pad}" y2="${y(50)}" stroke="#ece9e1" stroke-width="1"/>
    <line x1="${leftPad}" y1="${y(0)}" x2="${W - pad}" y2="${y(0)}" stroke="#e4e1d8" stroke-width="1"/>
    <text x="${leftPad - 6}" y="${y(100) + 3}" font-size="9" fill="#8c897e" text-anchor="end">100</text>
    <text x="${leftPad - 6}" y="${y(50) + 3}" font-size="9" fill="#8c897e" text-anchor="end">50</text>
    <text x="${leftPad - 6}" y="${y(0) + 3}" font-size="9" fill="#8c897e" text-anchor="end">0</text>
    ${
      projected.length
        ? `<rect x="${projStartX}" y="${pad}" width="${Math.max(
            0,
            W - pad - projStartX
          )}" height="${H - pad * 2}" fill="#f5f3ff" opacity="0.35"/>`
        : ""
    }
    <line x1="${projStartX}" y1="${pad}" x2="${projStartX}" y2="${H - pad}" stroke="#ddd6fe" stroke-width="1" stroke-dasharray="3,3"/>
    ${
      projected.length
        ? `<text x="${projStartX + 4}" y="${pad + 10}" font-size="9" fill="#7c3aed">Projection</text>`
        : ""
    }
    <path d="${toPathDyn(weekly)}" fill="none" stroke="#0d9488" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
    ${
      projected.length
        ? `<path d="${toBandPath(projUpper, projLower, weekly.length)}" fill="#7c3aed" opacity="0.16"/>`
        : ""
    }
    ${
      projected.length
        ? `<path d="${toPathDyn(
            [{ value: histLast }, ...projected],
            weekly.length - 1
          )}" fill="none" stroke="#7c3aed" stroke-width="2.8" stroke-dasharray="7,4" stroke-linecap="round" stroke-linejoin="round" opacity="0.95"/>`
        : ""
    }
    ${
      projected.length
        ? `<circle cx="${projStartX}" cy="${y(histLast)}" r="2.2" fill="#7c3aed"/>
           <circle cx="${projEndX}" cy="${projEndY}" r="2.8" fill="#7c3aed"/>
           <text x="${projEndX - 2}" y="${Math.max(12, projEndY - 6)}" font-size="9" fill="#7c3aed" text-anchor="end">Proj ${Math.round(
            projTarget
          )}</text>`
        : ""
    }
    <text x="${leftPad}" y="${H - 2}" font-size="9" fill="#8c897e">${esc(weekly[0]?.week)}</text>
    <text x="${W / 2}" y="${H - 2}" font-size="9" fill="#8c897e" text-anchor="middle">${esc(weekly[midIdx]?.week)}</text>
    <text x="${W - pad}" y="${H - 2}" font-size="9" fill="#8c897e" text-anchor="end">${esc(
      projected.length ? "Projected +52w" : weekly[weekly.length - 1]?.week
    )}</text>
  </svg>`;
}

function _simpleSlope(values) {
  if (!Array.isArray(values) || values.length < 2) return 0;
  return (Number(values[values.length - 1]) - Number(values[0])) / Math.max(1, values.length - 1);
}

function _loadScriptOnce(src) {
  return new Promise((resolve, reject) => {
    const existing = document.querySelector(`script[data-src="${src}"]`);
    if (existing && existing.dataset.loaded === "true") return resolve();
    if (existing) {
      existing.addEventListener("load", () => resolve(), { once: true });
      existing.addEventListener("error", () => reject(new Error(`Failed to load ${src}`)), { once: true });
      return;
    }
    const s = document.createElement("script");
    s.src = src;
    s.async = true;
    s.dataset.src = src;
    s.onload = () => {
      s.dataset.loaded = "true";
      resolve();
    };
    s.onerror = () => reject(new Error(`Failed to load ${src}`));
    document.head.appendChild(s);
  });
}

async function _ensureUsMapDeps() {
  if (window.d3 && window.topojson) return;
  await _loadScriptOnce("https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js");
  await _loadScriptOnce("https://cdn.jsdelivr.net/npm/topojson-client@3/dist/topojson-client.min.js");
}

async function _renderUsStateChoropleth(containerId, mapData, token) {
  const container = document.getElementById(containerId);
  if (!container) return;
  try {
    await _ensureUsMapDeps();
    if (token !== stateMapRenderToken) return;
    const d3 = window.d3;
    const topojson = window.topojson;
    if (!d3 || !topojson) throw new Error("Map libraries unavailable");

    const priceByFips = {};
    const sampleByFips = {};
    (mapData?.states || []).forEach((row) => {
      const abbr = String(row.state || "").trim().toUpperCase();
      const fips = STATE_ABBR_TO_FIPS[abbr];
      const price = Number(row.avgPrice);
      if (!fips || !Number.isFinite(price)) return;
      priceByFips[fips] = price;
      sampleByFips[fips] = Number(row.sampleSize || 0);
    });

    const values = Object.values(priceByFips);
    if (!values.length) {
      container.innerHTML = `<div class="stat-sub">No state-level prices available for this query.</div>`;
      return;
    }

    const us = await d3.json("https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json");
    if (token !== stateMapRenderToken) return;
    const states = topojson.feature(us, us.objects.states).features;
    const mesh = topojson.mesh(us, us.objects.states, (a, b) => a !== b);

    const width = 920;
    const height = 560;
    const projection = d3.geoAlbersUsa().fitSize([width, height], { type: "FeatureCollection", features: states });
    const path = d3.geoPath(projection);

    const minV = d3.min(values);
    const maxV = d3.max(values);
    const color = d3
      .scaleLinear()
      .domain([minV, maxV])
      .range(["#dbeafe", "#1d4ed8"]);

    const svg = d3
      .create("svg")
      .attr("viewBox", `0 0 ${width} ${height}`)
      .attr("class", "us-state-svg")
      .attr("role", "img")
      .attr("aria-label", "United States state price map");

    svg
      .append("g")
      .selectAll("path")
      .data(states)
      .join("path")
      .attr("d", path)
      .attr("class", "us-state-path")
      .attr("fill", (d) => {
        const fips = String(d.id).padStart(2, "0");
        return Object.prototype.hasOwnProperty.call(priceByFips, fips) ? color(priceByFips[fips]) : "#e5e7eb";
      })
      .append("title")
      .text((d) => {
        const fips = String(d.id).padStart(2, "0");
        const abbr = FIPS_TO_STATE_ABBR[fips] || fips;
        const p = priceByFips[fips];
        const n = sampleByFips[fips] || 0;
        return Number.isFinite(p) ? `${abbr}: $${p.toFixed(2)} (${n} comps)` : `${abbr}: no data`;
      });

    svg.append("path").attr("d", path(mesh)).attr("class", "us-state-borders");

    // Label only states we have data for, to keep map readable.
    const labelData = states.filter((d) => Object.prototype.hasOwnProperty.call(priceByFips, String(d.id).padStart(2, "0")));
    svg
      .append("g")
      .attr("class", "us-state-labels")
      .selectAll("text")
      .data(labelData)
      .join("text")
      .attr("x", (d) => path.centroid(d)[0])
      .attr("y", (d) => path.centroid(d)[1])
      .attr("text-anchor", "middle")
      .text((d) => FIPS_TO_STATE_ABBR[String(d.id).padStart(2, "0")] || "");

    container.innerHTML = "";
    container.appendChild(svg.node());
  } catch (err) {
    container.innerHTML = `<div class="stat-sub">State map failed to load (${esc(err?.message || "unknown error")}).</div>`;
  }
}

function buildStateHeatMapHTML(mapData) {
  const states = Array.isArray(mapData?.states) ? mapData.states : [];
  if (!states.length) return "";

  const granularity = String(mapData?.granularity || "state").toLowerCase();
  const title = granularity === "state" ? "U.S. State Price Heat Map" : "U.S. Approximate State Price Heat Map";
  const granularityNote =
    granularity === "state"
      ? "state-level"
      : "ZIP3-level (eBay active listings mask full ZIP/state)";
  const stateLookupNote = mapData?.approximateStateFromZip3
    ? "  state mapping inferred from ZIP3 lookup"
    : "";

  return `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">${title} <span class="live-badge" style="font-size:9px">LIVE eBay</span></div>
    <div class="stat-sub" style="margin-bottom:10px">${esc(
      mapData.source || "eBay"
    )} - ${granularityNote}${stateLookupNote} - darker = higher avg sold price (hover state for exact value)</div>
    <div class="us-state-wrap">
      <div id="us-state-choropleth" class="us-state-canvas">
        <div class="stat-sub">Rendering state map...</div>
      </div>
      <div class="us-state-legend">
        <span>Lower</span>
        <div class="us-state-gradient"></div>
        <span>Higher Avg Price</span>
      </div>
    </div>
  </div>`;
}

function renderResults() {
  const r = report;
  const n = newsData;
  const t = trendsData;
  const w = wtoData;

  const year = new Date().getFullYear();
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  const p = r.pricing || {};
  const timelineIsLive = r.timelineMethod === "google_zscore_live";

  const googleIsLive =
    t && Array.isArray(t.points) && t.points.length > 0 && hasNumber(t.score);
  const newsIsLive = n && hasNumber(n.score);
  const pricingIsLive =
    String(p.liveSource || "")
      .toLowerCase()
      .includes("ebay");
  const wtoIsLive = w && !w.warning && hasNumber(Number(w.latestTariffPercent));

  const liveLabelBits = [];
  if (newsIsLive) liveLabelBits.push("NewsAPI.org");
  if (googleIsLive) liveLabelBits.push("Google Trends");
  if (pricingIsLive) liveLabelBits.push("eBay");
  if (wtoIsLive) liveLabelBits.push("WTO");

  const liveLegendText =
    liveLabelBits.length > 0
      ? `Live data (${liveLabelBits.join(" + ")})`
      : "Live data (unavailable)";

  let html = "";

  // Download bar
  html += `<div class="download-bar">
    <div class="download-bar-left">
      <div class="download-bar-title">Report ready  "${esc(r.category)}"</div>
      <div class="download-bar-sub">Downloads as HTML  open in browser and File > Print > Save as PDF</div>
    </div>
    <button class="download-btn" onclick="downloadHTML()">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
      Download Report
    </button>
  </div>`;

  // Data legend
  html += `<div class="data-legend">
    <div class="data-legend-item"><div class="legend-dot live"></div>${esc(
      liveLegendText
    )}</div>
    <div class="data-legend-item"><div class="legend-dot ai"></div>AI estimate (OpenAI)</div>
  </div>`;

  // Report head
  html += `<div class="report-head">
    <div>
      <div class="report-title">Trend Report</div>
      <div class="report-category">"${esc(r.category)}" <em>analysis</em></div>
    </div>
    <div class="report-meta">
      <span class="curve-pill">${esc(r.trendCurveShape)}</span>
      <div style="margin-top:6px">Generated ${dateStr}</div>
    </div>
  </div>`;

  html += renderAgentTraceCard(r.agentTrace);

  // Signal scores
  const googleBadge = googleIsLive
    ? `<span class="live-badge">LIVE</span>`
    : `<span class="ai-badge">AI</span>`;
  const googleSub = googleIsLive
    ? `Live via Google Trends (pytrends)`
    : `AI estimate  live integration unavailable`;
  const ebayBadge = pricingIsLive
    ? `<span class="live-badge">LIVE</span>`
    : `<span class="ai-badge">AI</span>`;
  const signalGridClass = "three-col";

  html += `<div class="section-heading">Signal Scores</div>
  <div class="${signalGridClass}">
    <div class="stat-card ${googleIsLive ? "live-data" : ""}">
      <div class="stat-label">Google Search Interest ${googleBadge}</div>
      <div class="stat-value ${googleIsLive ? "teal" : signalColor(
        r.googleTrendScore
      )}">${r.googleTrendScore}<span style="font-size:14px;font-weight:500;color:var(--muted)">/100</span></div>
      <div class="stat-sub">${esc(googleSub)}</div>
    </div>
    <div class="stat-card live-data">
      <div class="stat-label">News Coverage <span class="live-badge">LIVE</span></div>
      <div class="stat-value teal">${r.newsScore}<span style="font-size:14px;font-weight:500;color:var(--muted)">/100</span></div>
      <div class="stat-sub">${
        n ? n.totalResults.toLocaleString() + " articles in recent period (up to 30 days)" : "Via NewsAPI.org"
      }</div>
    </div>
    <div class="stat-card ${pricingIsLive ? "live-data" : ""}">
      <div class="stat-label">eBay Pricing ${ebayBadge}</div>
      <div class="stat-value ${pricingIsLive ? "teal" : "blue"}">$${(p.currentAvgPrice || 0).toFixed(2)}</div>
      <div class="stat-sub">${
        pricingIsLive
          ? `Live avg sold price${p.liveSampleSize ? "  " + p.liveSampleSize + " comps" : ""}`
          : "AI estimate  live eBay unavailable"
      }</div>
    </div>
  </div>`;

  // News articles
  if (n && n.articles && n.articles.length > 0) {
    html += `<div class="section-card" style="margin-bottom:20px">
      <div class="news-articles-title"><span style="width:7px;height:7px;border-radius:50%;background:var(--teal);display:inline-block"></span> Live News Articles  recent period (up to 30 days) (${n.totalResults.toLocaleString()} total found)</div>
      <div class="news-articles">${n.articles
        .map(
          (a) => `
        <div class="news-article-item">
          <div class="news-article-title">${esc(a.title)}</div>
          <div class="news-article-meta"><span class="news-article-source">${esc(
            a.source
          )}</span><span>${esc(a.publishedAt)}</span></div>
        </div>`
        )
        .join("")}
      </div>
    </div>`;
  }

  if (t && Array.isArray(t.points) && t.points.length > 0) {
    html += `<div class="section-card" style="margin-bottom:20px">
      <div class="section-heading">Google Trends Interest <span class="live-badge" style="font-size:9px">LIVE</span></div>
      <div class="stat-sub" style="margin-bottom:10px">Historical window: last ${HISTORY_WEEKS} weeks (matches pricing history period)</div>
      <div class="chart-legend" style="margin-bottom:10px">
        <div class="cl-item"><div style="width:18px;height:2px;background:#0d9488;border-radius:2px"></div>Historical interest</div>
        <div class="cl-item"><div style="width:18px;height:0;border-top:2px dashed #7c3aed"></div>Projected interest</div>
        <div class="cl-item"><div style="width:18px;height:8px;background:#7c3aed;opacity:.2;border-radius:2px"></div>80% confidence band</div>
      </div>
      <div class="chart-wrap">${buildTrendsInterestSVG(t.points, Number(r.futureScore ?? r.presentScore ?? t.score))}</div>
    </div>`;
  }

  html += renderArimaRobustnessCard(r.arimaRobustness);

  // Trend velocity bars
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Trend Velocity ${
      timelineIsLive
        ? '<span class="live-badge" style="font-size:9px">LIVE Google</span>'
        : '<span class="ai-badge" style="font-size:9px">AI estimate</span>'
    }</div>
    <div class="trend-bar-row" id="velocity-bars">
      ${[
        ["Last Year", r.pastScore, "#d4d0c4"],
        ["This Year", r.presentScore, "#2563eb"],
        ["Next Year (Projected)", r.futureScore, "#16a34a"],
      ]
        .map(
          ([lbl, val, col]) => `
      <div>
        <div class="bar-item-label"><span>${lbl}</span><span>${val}/100</span></div>
        <div class="bar-track"><div class="bar-fill" data-width="${val}" style="width:0%;background:${col}"></div></div>
      </div>`
        )
        .join("")}
    </div>
  </div>`;

  // Timeline
  const timeline = [
    { period: "Last Year", year: year - 1, summary: r.pastSummary, badge: r.pastTrendBadge },
    { period: "This Year", year: year, summary: r.presentSummary, badge: r.presentTrendBadge },
    { period: "Forecast", year: year + 1, summary: r.futureSummary, badge: r.futureTrendBadge, future: true },
  ];
  html += `<div class="section-heading">Timeline ${
    timelineIsLive
      ? '<span class="live-badge" style="font-size:9px">LIVE Google</span>'
      : '<span class="ai-badge" style="font-size:9px">AI estimate</span>'
  }</div>
  <div class="three-col" style="margin-bottom:20px">${timeline
    .map(
      (tt) => `
    <div class="timeline-card${tt.future ? " future-card" : ""}">
      <div class="tc-period">${tt.period}</div>
      <div class="tc-year">${tt.year}</div>
      ${
        tt.badge
          ? `<div class="tc-badge ${badgeClass(tt.badge)}"><span>${badgeIcon(
              tt.badge
            )}</span> ${esc(tt.badge)}</div>`
          : ""
      }
      <div class="tc-body">${esc(tt.summary)}</div>
    </div>`
    )
    .join("")}
  </div>`;

  // Analysis sections
  const marketAnalysis = r.marketAnalysis || r.fullReport || "";
  const inputBreakdownAnalysis = r.inputBreakdownAnalysis || "";
  const competitionAnalysis = r.competitionAnalysis || "";
  const politicalAnalysis = r.politicalAnalysis || "";
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Market Analysis <span class="ai-badge" style="font-size:9px">AI generated</span></div>
    <div class="report-body">${esc(marketAnalysis)}</div>
  </div>`;
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Input Breakdown Analysis <span class="ai-badge" style="font-size:9px">AI generated</span></div>
    <div class="report-body">${esc(inputBreakdownAnalysis || "No input breakdown provided.")}</div>
  </div>`;
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Competition Analysis <span class="ai-badge" style="font-size:9px">AI generated</span></div>
    <div class="report-body">${esc(competitionAnalysis || "No competition analysis provided.")}</div>
  </div>`;
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Political Analysis <span class="ai-badge" style="font-size:9px">AI generated</span></div>
    <div class="report-body">${esc(politicalAnalysis || "No political analysis provided.")}</div>
  </div>`;

  if (w) {
    const partners = Array.isArray(w.partnerCandidateNames) && w.partnerCandidateNames.length
      ? w.partnerCandidateNames
      : Array.isArray(w.partnerCandidates)
      ? w.partnerCandidates
      : [];
    const partnerText = partners.length ? partners.join(", ") : "None";
    const partnerPreview = partners.length ? partners.slice(0, 3).join(", ") : "None";
    const indicatorExplain = explainWtoIndicator(w);
    html += `<div class="section-card" style="margin-bottom:20px">
      <div class="section-heading">Trade & Tariff Context ${
        wtoIsLive ? '<span class="live-badge" style="font-size:9px">LIVE WTO</span>' : '<span class="ai-badge" style="font-size:9px">fallback/none</span>'
      }</div>
      <div class="four-col" style="margin-bottom:14px">
        <div class="stat-card ${wtoIsLive ? "live-data" : ""}">
          <div class="stat-label">Latest Tariff</div>
          <div class="stat-value ${wtoIsLive ? "teal" : "amber"}">${
            hasNumber(Number(w.latestTariffPercent)) ? Number(w.latestTariffPercent).toFixed(1) + "%" : "N/A"
          }</div>
          <div class="stat-sub">Year ${esc(w.latestYear || "N/A")}</div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Partner Candidates</div>
          <div class="stat-value blue" style="font-size:14px;line-height:1.25">${esc(partnerPreview)}</div>
          <div class="stat-sub">Inference: ${esc(w.partnerInferenceMethod || "none")}</div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Indicator</div>
          <div class="stat-value purple" style="font-size:16px;line-height:1.25">${esc(w.indicator || "N/A")}</div>
          <div class="stat-sub">${esc(indicatorExplain)}</div>
        </div>
        <div class="stat-card">
          <div class="stat-label">Fallback Applied</div>
          <div class="stat-value ${w.fallbackApplied ? "amber" : "green"}">${w.fallbackApplied ? "YES" : "NO"}</div>
          <div class="stat-sub">${esc(w.periodRange || "")}  ${esc(w.targetedMatchLevel || "n/a")}  ${esc(w.confidence || "n/a")}</div>
        </div>
      </div>
      <div class="stat-sub">Partner candidates: ${esc(partnerText)}</div>
      <div class="stat-sub" style="margin-top:4px">HS Category: ${esc(w.usedHsCategory || w.hsCategory || "Not specified")}</div>
      ${
        w.warning
          ? `<div class="disclaimer-box" style="margin-top:10px">WTO note: ${esc(w.warning)}</div>`
          : ""
      }
    </div>`;
  }

  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Ask Follow-up Questions <span class="ai-badge" style="font-size:9px">ChatGPT</span></div>
    <div class="followup-sub">Ask for deeper interpretation of this report, assumptions, or scenario checks.</div>
    <div id="followup-thread" class="followup-thread"></div>
    <div class="followup-input-row">
      <input id="followup-input" class="followup-input" placeholder="Ask a follow-up question about this report..." />
      <button id="followup-ask-btn" class="followup-btn">Ask</button>
    </div>
  </div>`;

  // Pricing section
  if (p.currentAvgPrice) {
    html += `<div class="section-heading">Price History &amp; Forecast ${
      pricingIsLive
        ? '<span class="live-badge" style="font-size:9px">LIVE eBay</span>'
        : '<span class="ai-badge" style="font-size:9px">AI estimate</span>'
    }</div>
    <div class="section-card" style="margin-bottom:20px">
      <div class="stat-sub" style="margin-bottom:12px">Historical window: last ${HISTORY_WEEKS} weeks</div>
      <div class="four-col" style="margin-bottom:24px">
        <div class="stat-card ${pricingIsLive ? "live-data" : ""}"><div class="stat-label">Avg. Price Today ${
          pricingIsLive ? '<span class="live-badge">LIVE</span>' : '<span class="ai-badge">AI</span>'
        }</div><div class="stat-value blue">$${p.currentAvgPrice?.toFixed(
          2
        )}</div><div class="stat-sub">$${p.typicalPriceRangeLow}$${p.typicalPriceRangeHigh} typical${
          pricingIsLive && p.liveSampleSize ? `  ${p.liveSampleSize} listings` : ""
        }</div></div>
        <div class="stat-card"><div class="stat-label">Year-over-Year</div><div class="stat-value ${
          p.priceChangeYoY >= 0 ? "green" : "red"
        }">${p.priceChangeYoY >= 0 ? "+" : ""}${p.priceChangeYoY?.toFixed(
      1
    )}%</div><div class="stat-sub">Trend: ${esc(p.priceTrend)}</div></div>
        <div class="stat-card"><div class="stat-label">12-Month Forecast</div><div class="stat-value purple">$${p.forecastAvgPrice12mo?.toFixed(
          2
        )}</div><div class="stat-sub">Projected average</div></div>
        <div class="stat-card"><div class="stat-label">24-Month Forecast</div><div class="stat-value purple">$${p.forecastAvgPrice24mo?.toFixed(
          2
        )}</div><div class="stat-sub">Outlook: ${esc(p.priceOutlook)}</div></div>
      </div>
      <div class="chart-legend">
        <div class="cl-item"><div style="width:18px;height:2px;background:#2563eb;border-radius:2px"></div>Historical</div>
        <div class="cl-item"><div style="width:18px;height:0;border-top:2px dashed #7c3aed"></div>Projected</div>
      </div>
      <div class="chart-wrap">${buildSparklineSVG(p.monthlyHistory)}</div>
      <div class="divider"></div>
      <div class="two-col">
        <div><div class="driver-col-label bull">Price-Up Factors</div>${(p.priceBullishDrivers || [])
          .map((d) => `<div class="driver-item bull"><span>?</span>${esc(d)}</div>`)
          .join("")}</div>
        <div><div class="driver-col-label bear">Price-Down Factors</div>${(p.priceBearishDrivers || [])
          .map((d) => `<div class="driver-item bear"><span>?</span>${esc(d)}</div>`)
          .join("")}</div>
      </div>
      <div class="verdict-box"><div class="verdict-label">Verdict</div><div class="verdict-text">${esc(
        p.pricingVerdict
      )}</div></div>
    </div>`;
  }

  if (ebayMapData && Array.isArray(ebayMapData.states) && ebayMapData.states.length > 0) {
    html += buildStateHeatMapHTML(ebayMapData);
  }

  // Keywords
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Keyword Signals <span class="ai-badge" style="font-size:9px">AI estimate</span></div>
    <div class="kw-group"><div class="kw-group-label">Rising Now</div><div class="chip-group">${(r.hotKeywords || [])
      .map((k) => `<div class="chip hot">${esc(k)}</div>`)
      .join("")}</div></div>
    <div class="kw-group"><div class="kw-group-label">Fading</div><div class="chip-group">${(r.warmKeywords || [])
      .map((k) => `<div class="chip warm">${esc(k)}</div>`)
      .join("")}</div></div>
    <div class="kw-group"><div class="kw-group-label">Declining</div><div class="chip-group">${(r.coldKeywords || [])
      .map((k) => `<div class="chip cold">${esc(k)}</div>`)
      .join("")}</div></div>
    <div class="kw-group" style="margin-bottom:0"><div class="kw-group-label">Keyword Summary</div><div class="chip-group">${(r.hotKeywords || [])
      .slice(0, 3)
      .map((k) => `<div class="chip hot">${esc(k)}</div>`)
      .join("")}</div></div>
  </div>`;

  // Brands
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Brand Intelligence <span class="ai-badge" style="font-size:9px">AI estimate</span></div>
    <div class="two-col">
      <div><div class="kw-group-label" style="margin-bottom:10px">Leading Brands</div>${(r.leadingBrands || [])
        .map((b, i) => `<div class="brand-item lead"><div class="brand-rank lead">${i + 1}</div>${esc(b)}</div>`)
        .join("")}</div>
      <div><div class="kw-group-label" style="margin-bottom:10px">Rising Challengers</div>${(r.risingBrands || [])
        .map((b) => `<div class="brand-item rise"><div class="brand-rank rise">?</div>${esc(b)}</div>`)
        .join("")}</div>
    </div>
  </div>`;

  // Products
  html += `<div class="section-card" style="margin-bottom:20px">
    <div class="section-heading">Product Signals <span class="ai-badge" style="font-size:9px">AI estimate</span></div>
    <div class="kw-group-label" style="margin-bottom:10px">Trending Now</div>
    <div class="two-col" style="margin-bottom:16px">${(r.topProducts || [])
      .map((p2) => `<div class="product-item"><div class="p-status hot">Trending</div>${esc(p2)}</div>`)
      .join("")}</div>
    <div class="kw-group-label" style="margin-bottom:10px">Losing Steam</div>
    <div class="two-col">${(r.fadingProducts || [])
      .map((p2) => `<div class="product-item fading"><div class="p-status fade">Fading</div>${esc(p2)}</div>`)
      .join("")}</div>
  </div>`;

  // Sources + disclaimer
  html += `<div class="section-heading">Data Sources &amp; Methodology</div>
  <div class="section-card">
    ${DATA_SOURCES.map(
      (src, i) => `<div class="source-item">
      <div class="source-num">${i + 1}</div>
      <div>
        <div class="source-name">${esc(src.name)} <span class="source-tag ${
        src.tag
      }">${src.tag === "live" ? "LIVE DATA" : "AI ESTIMATE"}</span></div>
        <div class="source-type">${esc(src.type)}</div>
        <div class="source-desc">${esc(src.desc)}</div>
      </div>
    </div>`
    ).join("")}
    <div class="disclaimer-box" style="margin-top:16px">
      <strong>Disclaimer:</strong>
      News coverage and Google Trends are fetched live (best-effort; Google Trends may be rate-limited).
      Pricing uses live eBay sold/completed data when available; otherwise it falls back to active listings or AI estimates.
      All other non-live scores and forecasts are AI-generated estimates.
      Always verify with primary sources before making financial, purchasing, or strategic decisions.
    </div>
  </div>`;

  $("results-section").innerHTML = html;
  $("results-section").classList.remove("hidden");
  initFollowupChat();

  if (ebayMapData && Array.isArray(ebayMapData.states) && ebayMapData.states.length > 0) {
    stateMapRenderToken += 1;
    _renderUsStateChoropleth("us-state-choropleth", ebayMapData, stateMapRenderToken);
  }

  // Animate bars after paint
  requestAnimationFrame(() => {
    setTimeout(() => {
      document.querySelectorAll(".bar-fill[data-width]").forEach((el) => {
        el.style.width = el.dataset.width + "%";
      });
    }, 100);
  });
}

function renderFollowupThread() {
  const thread = $("followup-thread");
  if (!thread) return;
  if (!followupMessages.length) {
    thread.innerHTML = `<div class="followup-empty">No follow-up questions yet.</div>`;
    return;
  }
  thread.innerHTML = followupMessages
    .map(
      (m) => `<div class="followup-msg ${m.role === "assistant" ? "assistant" : "user"}">
        <div class="followup-role">${m.role === "assistant" ? "Assistant" : "You"}</div>
        <div class="followup-text">${esc(m.content || "")}</div>
        ${m.role === "assistant" ? renderAgentTraceMini(m.agentTrace) : ""}
      </div>`
    )
    .join("");
  thread.scrollTop = thread.scrollHeight;
}

async function askFollowupQuestion() {
  const input = $("followup-input");
  const btn = $("followup-ask-btn");
  if (!input || !btn || !report) return;
  const question = (input.value || "").trim();
  if (!question) return;

  followupMessages.push({ role: "user", content: question });
  followupMessages.push({ role: "assistant", content: "Thinking..." });
  input.value = "";
  renderFollowupThread();
  btn.disabled = true;

  try {
    const resp = await fetch("/api/chat_followup", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        category: report.category || "",
        question,
        report,
        history: followupMessages.filter((m) => m.content !== "Thinking..."),
      }),
    });
    if (!resp.ok) {
      let msg = "Follow-up failed";
      try {
        const d = await resp.json();
        msg = d.detail || msg;
      } catch (_) {}
      throw new Error(msg);
    }
    const data = await resp.json();
    const answer = String(data.answer || "").trim() || "No response returned.";
    followupMessages.pop(); // remove Thinking...
    followupMessages.push({ role: "assistant", content: answer, agentTrace: data.agentTrace || null });
  } catch (err) {
    followupMessages.pop(); // remove Thinking...
    followupMessages.push({ role: "assistant", content: `Error: ${err.message || String(err)}` });
  } finally {
    btn.disabled = false;
    renderFollowupThread();
  }
}

function initFollowupChat() {
  const input = $("followup-input");
  const btn = $("followup-ask-btn");
  if (!input || !btn) return;
  renderFollowupThread();
  btn.onclick = () => askFollowupQuestion();
  input.onkeydown = (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      askFollowupQuestion();
    }
  };
}

// -- Download HTML report -----------------------------------------------------
function downloadHTML() {
  const r = report;
  const n = newsData;
  const t = trendsData;
  const w = wtoData;

  const html = buildReportHTML(r, n, t, w);

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `Market Intel Agent_${r.category.replace(/\s+/g, "_")}_Report.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function buildReportHTML(r, n, t, w) {
  const date = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const year = new Date().getFullYear();
  const p = r.pricing || {};

  const newsScore = hasNumber(n?.score) ? n.score : r.newsScore;
  const googleScore = hasNumber(t?.score) ? t.score : r.googleTrendScore;

  const googleIsLive =
    t && Array.isArray(t.points) && t.points.length > 0 && hasNumber(t.score);
  const pricingIsLive =
    String(p.liveSource || "")
      .toLowerCase()
      .includes("ebay");
  const wtoIsLive = w && !w.warning && hasNumber(Number(w.latestTariffPercent));
  const timelineIsLive = r.timelineMethod === "google_zscore_live";
  const chip = (txt, cls) => `<span class="chip ${cls}">${esc(txt)}</span>`;
  const badgeCls = (b = "") => {
    const u = b.toUpperCase();
    if (u.includes("RISING")) return "badge-green";
    if (u.includes("PEAKED") || u.includes("PLATEAU")) return "badge-amber";
    if (u.includes("DECLINING")) return "badge-red";
    if (u.includes("EMERGING")) return "badge-purple";
    return "badge-gray";
  };

  const sparkSVG = buildSparklineSVG(p.monthlyHistory);
  const trendsSVG = buildTrendsInterestSVG(t?.points || [], Number(r?.futureScore ?? r?.presentScore ?? t?.score));

  const newsHTML = n?.articles?.length
    ? `<div style="margin-top:14px"><div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:#0d9488;margin-bottom:8px">Live News Articles (recent period, up to 30 days)</div>${n.articles
        .map(
          (a) =>
            `<div style="padding:8px 10px;border:1px solid #99f6e4;border-radius:5px;background:#f0fdfa;margin-bottom:5px"><div style="font-size:11px;font-weight:600;color:#1a1814;margin-bottom:2px">${esc(
              a.title
            )}</div><div style="font-size:10px;color:#8c897e"><span style="color:#0d9488;font-weight:600">${esc(
              a.source
            )}</span>  ${esc(a.publishedAt)}</div></div>`
        )
        .join("")}</div>`
    : "";
  const agentTrace = r?.agentTrace && typeof r.agentTrace === "object" ? r.agentTrace : null;
  const toolPlan = Array.isArray(agentTrace?.toolPlan) ? agentTrace.toolPlan : [];
  const additionalTools = Array.isArray(agentTrace?.additionalTools) ? agentTrace.additionalTools : [];
  const toolRuns = Array.isArray(agentTrace?.toolRuns) ? agentTrace.toolRuns : [];
  const agentWarnings = Array.isArray(agentTrace?.warnings) ? agentTrace.warnings : [];
  const reflection = agentTrace?.reflection || {};
  const agentTraceHTML = agentTrace
    ? `<div class="sec-title">Agent Workflow <span class="badge-pill live" style="font-size:8px">plan-act-observe</span></div>
  <div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px">
    <span class="chip sub">1. Planned</span>
    <span class="chip sub">2. Gathered Evidence</span>
    <span class="chip sub">3. Reflected</span>
  </div>
  <div class="grid-2" style="margin-bottom:10px">
    <div class="stat" style="border-color:#99f6e4;background:#fcfffd">
      <div class="stat-lbl" style="color:#0d9488">Objective</div>
      <div class="report-body" style="font-size:11px">${esc(cleanPresentationText(agentTrace.objective || "No objective recorded."))}</div>
    </div>
    <div class="stat" style="border-color:#99f6e4;background:#fcfffd">
      <div class="stat-lbl" style="color:#0d9488">Why These Tools</div>
      <div class="report-body" style="font-size:11px">${esc(cleanPresentationText(agentTrace.planReasoning || "No planner notes recorded."))}</div>
    </div>
  </div>
  <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:#8c897e;margin:8px 0 6px">Selected Tools</div>
  <div class="chip-group" style="margin-bottom:10px">${
    toolPlan.length
      ? toolPlan.map((tool) => `<span class="chip sub">${esc(humanizeToolName(tool))}</span>`).join("")
      : `<span style="font-size:10px;color:#8c897e">No tools recorded.</span>`
  }</div>
  <div class="grid-2" style="margin-bottom:10px">
    <div class="stat">
      <div class="stat-lbl">Decision Summary</div>
      <div class="stat-sub">${esc(formatConfidenceLabel(reflection.confidence || ""))}</div>
      <div class="report-body" style="font-size:11px">${esc(cleanPresentationText(reflection.stopReason || "No reflection summary recorded."))}</div>
      <div class="stat-sub" style="margin-top:8px">Additional evidence gathered: ${esc(
        additionalTools.length ? additionalTools.map(humanizeToolName).join(", ") : "none needed"
      )}</div>
    </div>
    <div class="stat">
      <div class="stat-lbl">Clarification Check</div>
      <div class="report-body" style="font-size:11px">${esc(
        agentTrace.clarificationRequested && agentTrace.clarifyingQuestion
          ? `The agent considered asking: ${cleanPresentationText(agentTrace.clarifyingQuestion)}`
          : "No clarification was needed before analysis."
      )}</div>
    </div>
  </div>
  ${
    toolRuns.length
      ? `<div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:#8c897e;margin:8px 0 6px">Evidence Collected</div>
  <div class="grid-2">${toolRuns
    .map(
      (run) => `<div class="stat${run.status === "error" ? "" : " live"}">
      <div class="stat-lbl">${esc(humanizeToolName(run.tool || ""))} <span class="badge-pill ${
        run.status === "error" ? "ai" : "live"
      }">${esc(run.status === "error" ? "issue" : "used")}</span></div>
      <div class="report-body" style="font-size:11px">${esc(summarizeAgentRun(run))}</div>
    </div>`
    )
    .join("")}</div>`
      : ""
  }
  ${
    agentWarnings.length
      ? `<div class="disclaimer" style="margin-top:10px">Warnings: ${esc(agentWarnings.join(" | "))}</div>`
      : ""
  }`
    : "";
  const followupHTML = Array.isArray(followupMessages) && followupMessages.length
    ? `<div class="sec-title">Follow-up Conversation <span class="badge-pill ai" style="font-size:8px">ChatGPT</span></div>
  <div style="margin-bottom:10px">${followupMessages
      .map(
        (m) => `<div style="border:1px solid #e4e1d8;border-radius:7px;padding:10px 12px;background:${m.role === "assistant" ? "#f0fdfa" : "#eff4ff"};margin-bottom:8px">
      <div style="font-size:9px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:#8c897e;margin-bottom:4px">${m.role === "assistant" ? "Assistant" : "You"}</div>
      <div style="font-size:12px;line-height:1.65;color:#4a4740;white-space:pre-wrap">${esc(m.content || "")}</div>
      ${
        m.role === "assistant" && m.agentTrace
          ? `<div style="margin-top:8px;padding-top:8px;border-top:1px dashed #99f6e4">
        <div style="font-size:9px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:#0d9488;margin-bottom:4px">Workflow summary</div>
        <div style="font-size:10px;color:#4a4740;line-height:1.55">${esc(cleanPresentationText(m.agentTrace.objective || "Follow-up evidence gathering"))}</div>
        <div style="font-size:10px;color:#8c897e;line-height:1.55;margin-top:4px">Tools: ${esc(
          Array.isArray(m.agentTrace.toolPlan) && m.agentTrace.toolPlan.length
            ? m.agentTrace.toolPlan.map(humanizeToolName).join(", ")
            : "none recorded"
        )}</div>
      </div>`
          : ""
      }
    </div>`
      )
      .join("")}</div>`
    : "";
  const wtoHTML = w
    ? (() => {
        const partnerList =
          Array.isArray(w.partnerCandidateNames) && w.partnerCandidateNames.length
            ? w.partnerCandidateNames
            : Array.isArray(w.partnerCandidates)
            ? w.partnerCandidates
            : [];
        const partnerPreview = partnerList.length ? partnerList.slice(0, 3).join(", ") : "None";
        const indicatorExplain = explainWtoIndicator(w);
        return `<div class="sec-title">Trade & Tariff Context <span class="badge-pill ${
          wtoIsLive ? "live" : "ai"
        }" style="font-size:8px">${wtoIsLive ? "LIVE WTO" : "fallback/none"}</span></div>
  <div class="grid-3">
    <div class="stat${wtoIsLive ? " live" : ""}">
      <div class="stat-lbl">Latest Tariff</div>
      <div class="stat-val c-${wtoIsLive ? "teal" : "amber"}">${
        hasNumber(Number(w.latestTariffPercent)) ? Number(w.latestTariffPercent).toFixed(1) + "%" : "N/A"
      }</div>
      <div class="stat-sub">Year ${esc(w.latestYear || "N/A")}</div>
    </div>
    <div class="stat">
      <div class="stat-lbl">Partner Candidates</div>
      <div class="stat-val c-blue" style="font-size:14px;line-height:1.25">${esc(partnerPreview)}</div>
      <div class="stat-sub">Inference: ${esc(w.partnerInferenceMethod || "none")}</div>
    </div>
    <div class="stat">
      <div class="stat-lbl">Indicator</div>
      <div class="stat-val c-purple" style="font-size:16px;line-height:1.25">${esc(w.indicator || "N/A")}</div>
      <div class="stat-sub">${esc(indicatorExplain)}</div>
    </div>
    <div class="stat">
      <div class="stat-lbl">Fallback Applied</div>
      <div class="stat-val c-${w.fallbackApplied ? "amber" : "green"}">${w.fallbackApplied ? "YES" : "NO"}</div>
      <div class="stat-sub">${esc(w.periodRange || "")}  ${esc(w.targetedMatchLevel || "n/a")}  ${esc(w.confidence || "n/a")}</div>
    </div>
  </div>
  <div style="font-size:10px;color:#8c897e;margin-top:8px">Partner candidates: ${esc(
    partnerList.length ? partnerList.join(", ") : "None"
  )}</div>
  <div style="font-size:10px;color:#8c897e;margin-top:4px">HS Category: ${esc(
    w.usedHsCategory || w.hsCategory || "Not specified"
  )}</div>
  ${
    w.warning
      ? `<div class="disclaimer" style="margin-top:10px">WTO note: ${esc(w.warning)}</div>`
      : ""
  }`;
      })()
    : "";


  // NOTE: This download HTML is intentionally self-contained and mirrors your prior output style.
  // It labels Google as LIVE only if trendsData was available at render-time.
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Market Intel Agent  ${esc(
    r.category
  )}</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;font-size:13px;color:#1a1814;background:#fff;line-height:1.5}.page{max-width:780px;margin:0 auto;padding:40px 40px 60px}.rpt-header{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:16px;border-bottom:3px solid #2563eb;margin-bottom:24px}.rpt-logo{font-size:18px;font-weight:800;color:#2563eb}.rpt-meta{text-align:right;font-size:11px;color:#8c897e;line-height:1.8}h1{font-size:26px;font-weight:700;letter-spacing:-0.02em;margin-bottom:4px}h1 em{color:#2563eb;font-style:italic}.sub{font-size:11px;color:#8c897e;margin-bottom:20px}.sec-title{font-size:10px;font-weight:700;letter-spacing:0.09em;text-transform:uppercase;color:#8c897e;margin:22px 0 10px;padding-top:16px;border-top:1px solid #e4e1d8}.grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:4px}.grid-4{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:4px}.grid-2{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{background:#f8f7f4;border:1px solid #e4e1d8;border-radius:7px;padding:12px 14px;position:relative;overflow:hidden}.stat.live{border-color:#99f6e4}.stat.live::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:#0d9488}.stat-lbl{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:#8c897e;margin-bottom:5px}.stat-val{font-size:22px;font-weight:800;line-height:1;margin-bottom:3px;letter-spacing:-0.02em}.stat-sub{font-size:10px;color:#8c897e}.c-blue{color:#2563eb}.c-green{color:#16a34a}.c-red{color:#dc2626}.c-purple{color:#7c3aed}.c-amber{color:#d97706}.c-teal{color:#0d9488}.badge-pill{display:inline-block;font-size:8px;font-weight:700;padding:1px 6px;border-radius:10px;margin-left:6px;vertical-align:middle}.badge-pill.live{background:#f0fdfa;color:#0d9488;border:1px solid #99f6e4}.badge-pill.ai{background:#f5f3ff;color:#7c3aed;border:1px solid #ddd6fe}.bar-row{margin-bottom:9px}.bar-lbl{display:flex;justify-content:space-between;font-size:11px;color:#4a4740;margin-bottom:4px}.bar-lbl span:last-child{font-weight:700}.bar-track{height:7px;background:#f1efe9;border-radius:4px;overflow:hidden}.bar-fill{height:100%;border-radius:4px}.tl-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:4px}.tl-box{border:1px solid #e4e1d8;border-radius:7px;padding:14px;background:#f8f7f4}.tl-box.future{border-color:#bfcff8;background:#eff4ff}.tl-period{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:0.07em;color:#8c897e;margin-bottom:2px}.future .tl-period{color:#2563eb}.tl-year{font-size:18px;font-weight:800;margin-bottom:7px}.badge{display:inline-block;font-size:9px;font-weight:700;padding:2px 8px;border-radius:20px;margin-bottom:7px}.badge-green{background:#f0fdf4;color:#16a34a;border:1px solid #bbf7d0}.badge-amber{background:#fffbeb;color:#d97706;border:1px solid #fde68a}.badge-red{background:#fef2f2;color:#dc2626;border:1px solid #fecaca}.badge-purple{background:#f5f3ff;color:#7c3aed;border:1px solid #ddd6fe}.badge-gray{background:#f1efe9;color:#4a4740;border:1px solid #e4e1d8}.tl-body{font-size:10.5px;color:#4a4740;line-height:1.6}.report-body{font-size:12.5px;color:#4a4740;line-height:1.75;white-space:pre-wrap}.chip-group{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:5px}.chip{font-size:11px;font-weight:500;padding:4px 10px;border-radius:20px;border:1px solid #e4e1d8;color:#4a4740;background:#f1efe9}.chip.hot{background:#eff4ff;color:#2563eb;border-color:#bfcff8}.chip.warm{background:#fffbeb;color:#d97706;border-color:#fde68a}.chip.cold{background:#f1efe9;color:#8c897e;text-decoration:line-through}.chip.sub{background:#f5f3ff;color:#7c3aed;border-color:#ddd6fe}.kw-lbl{font-size:9.5px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;color:#8c897e;margin:10px 0 5px}.brand-row{display:flex;align-items:center;gap:8px;padding:8px 12px;border:1px solid #e4e1d8;border-radius:5px;margin-bottom:5px;font-size:12px;font-weight:500;background:#f8f7f4}.brand-row.lead{border-color:#bfcff8;background:#eff4ff}.brand-row.rise{border-color:#bbf7d0;background:#f0fdf4}.brand-num{width:18px;height:18px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:800;flex-shrink:0}.brand-num.lead{background:#2563eb;color:white}.brand-num.rise{background:#16a34a;color:white}.prod-box{padding:9px 11px;border:1px solid #e4e1d8;border-radius:5px;background:#f8f7f4;font-size:11px;color:#4a4740}.ps{font-size:8.5px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:3px}.ps.hot{color:#16a34a}.ps.fade{color:#8c897e}.prod-box.fading{opacity:0.6}.drv-lbl{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:8px}.drv-lbl.bull{color:#16a34a}.drv-lbl.bear{color:#dc2626}.drv{display:flex;gap:6px;padding:7px 10px;border-radius:5px;margin-bottom:5px;font-size:11px;line-height:1.5;color:#4a4740}.drv.bull{background:#f0fdf4;border:1px solid #bbf7d0}.drv.bear{background:#fef2f2;border:1px solid #fecaca}.verdict{padding:12px 16px;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:7px;display:flex;gap:12px;margin-top:14px}.verdict-lbl{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:0.07em;color:#7c3aed;white-space:nowrap}.verdict-txt{font-size:11.5px;color:#4a4740;line-height:1.65}.src-row{display:flex;gap:12px;padding:12px 0;border-bottom:1px solid #e4e1d8}.src-row:last-child{border-bottom:none}.src-num{width:20px;height:20px;border-radius:50%;background:#f1efe9;border:1px solid #e4e1d8;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:800;color:#8c897e;flex-shrink:0}.src-name{font-size:12px;font-weight:700;margin-bottom:1px}.src-type{font-size:9.5px;color:#8c897e;margin-bottom:4px;font-family:monospace}.src-desc{font-size:11px;color:#4a4740;line-height:1.5}.disclaimer{background:#fffbeb;border:1px solid #fde68a;border-radius:7px;padding:12px 16px;font-size:11px;color:#92400e;line-height:1.6;margin-top:14px}.footer{margin-top:32px;padding-top:12px;border-top:1px solid #e4e1d8;font-size:10px;color:#8c897e;display:flex;justify-content:space-between}</style></head><body><div class="page">
  <div class="rpt-header"><div><div class="rpt-logo">Market Intel Agent</div><div style="font-size:10px;color:#8c897e;margin-top:2px">Market Intelligence</div></div><div class="rpt-meta">Generated ${date}<br>Curve: ${esc(
    r.trendCurveShape
  )}<br>News: Live via NewsAPI.org<br>Google: ${
    googleIsLive ? "Live via Google Trends" : "AI estimate"
  }</div></div>
  <h1>"${esc(r.category)}" <em>Analysis</em></h1><div class="sub">Trend & Pricing Report  ${date}</div>
  <div style="display:flex;gap:12px;margin-bottom:16px;font-size:10px;color:#4a4740;align-items:center">
    <span style="display:flex;align-items:center;gap:4px"><span style="width:8px;height:8px;border-radius:50%;background:#0d9488;display:inline-block"></span> Live data (NewsAPI${googleIsLive ? " + Google Trends" : ""}${pricingIsLive ? " + eBay" : ""}${wtoIsLive ? " + WTO" : ""})</span>
    <span style="display:flex;align-items:center;gap:4px"><span style="width:8px;height:8px;border-radius:50%;background:#7c3aed;display:inline-block"></span> AI estimate (OpenAI)</span>
  </div>

  ${agentTraceHTML}

  <div class="sec-title">Signal Scores</div>
  <div class="grid-4">
    <div class="stat${googleIsLive ? " live" : ""}">
      <div class="stat-lbl">Google Search Interest <span class="badge-pill ${
        googleIsLive ? "live" : "ai"
      }">${googleIsLive ? "LIVE" : "AI"}</span></div>
      <div class="stat-val ${googleScore >= 70 ? "c-green" : "c-blue"}">${googleScore}<span style="font-size:13px;color:#8c897e">/100</span></div>
      <div class="stat-sub">${
        googleIsLive ? "Live via Google Trends (pytrends)" : "AI estimate"
      }</div>
    </div>
    <div class="stat live"><div class="stat-lbl">News Coverage <span class="badge-pill live">LIVE</span></div><div class="stat-val c-teal">${newsScore}<span style="font-size:13px;color:#8c897e">/100</span></div><div class="stat-sub">${
      n?.totalResults?.toLocaleString() || ""
    } articles in recent period (up to 30 days)</div></div>
    <div class="stat${pricingIsLive ? " live" : ""}"><div class="stat-lbl">eBay Pricing <span class="badge-pill ${
      pricingIsLive ? "live" : "ai"
    }">${pricingIsLive ? "LIVE" : "AI"}</span></div><div class="stat-val c-${
      pricingIsLive ? "teal" : "blue"
    }">$${(p.currentAvgPrice || 0).toFixed(2)}</div><div class="stat-sub">${
      pricingIsLive
        ? `Live avg sold price${p.liveSampleSize ? "  " + p.liveSampleSize + " comps" : ""}`
        : "AI estimate"
    }</div></div>
  </div>
  ${newsHTML}
  ${
    trendsSVG
      ? `<div class="sec-title">Google Trends Interest <span class="badge-pill live" style="font-size:8px">LIVE</span></div>
  <div style="font-size:10px;color:#8c897e;margin-bottom:8px">Historical window: last ${HISTORY_WEEKS} weeks (matches pricing history period)</div>
  <div style="display:flex;gap:14px;align-items:center;margin-bottom:8px;font-size:10px;color:#8c897e">
    <span style="display:flex;gap:6px;align-items:center"><span style="width:16px;height:2px;background:#0d9488;display:inline-block"></span>Historical</span>
    <span style="display:flex;gap:6px;align-items:center"><span style="width:16px;height:0;border-top:2px dashed #7c3aed;display:inline-block"></span>Projected</span>
    <span style="display:flex;gap:6px;align-items:center"><span style="width:16px;height:8px;background:#7c3aed;opacity:.2;border-radius:2px;display:inline-block"></span>80% CI</span>
  </div>
  ${trendsSVG}`
      : ""
  }

  ${(() => {
    const ar = r.arimaRobustness;
    if (!ar || typeof ar !== "object") return "";
    const adfText = hasNumber(ar.adfPValue) ? Number(ar.adfPValue).toFixed(4) : "n/a";
    const lbText = hasNumber(ar.ljungBoxPValue) ? Number(ar.ljungBoxPValue).toFixed(4) : "n/a";
    return `<div class="sec-title">ARIMA Robustness <span class="badge-pill ai" style="font-size:8px">evidence</span></div>
  <div class="grid-4">
    <div class="stat"><div class="stat-lbl">Specification</div><div class="stat-val c-purple">${esc(ar.modelOrder || "ARIMA")}</div><div class="stat-sub">Train ${esc(ar.trainingPoints || "n/a")}  Holdout ${esc(ar.holdoutPoints || "n/a")}</div></div>
    <div class="stat"><div class="stat-lbl">Holdout RMSE</div><div class="stat-val c-blue">${esc(hasNumber(ar.holdoutRMSE) ? Number(ar.holdoutRMSE).toFixed(2) : "n/a")}</div><div class="stat-sub">Naive ${esc(hasNumber(ar.naiveRMSE) ? Number(ar.naiveRMSE).toFixed(2) : "n/a")}  Mean ${esc(hasNumber(ar.rollingMeanRMSE) ? Number(ar.rollingMeanRMSE).toFixed(2) : "n/a")}</div></div>
    <div class="stat"><div class="stat-lbl">ADF p-value</div><div class="stat-val c-${hasNumber(ar.adfPValue) && Number(ar.adfPValue) < 0.05 ? "green" : "amber"}">${esc(adfText)}</div><div class="stat-sub">Difference order ${esc(ar.differenceOrder || 1)}</div></div>
    <div class="stat"><div class="stat-lbl">Ljung-Box p</div><div class="stat-val c-${hasNumber(ar.ljungBoxPValue) && Number(ar.ljungBoxPValue) > 0.05 ? "green" : "amber"}">${esc(lbText)}</div><div class="stat-sub">AIC ${esc(ar.aic ?? "n/a")}  BIC ${esc(ar.bic ?? "n/a")}</div></div>
  </div>
  <div style="font-size:10px;color:#8c897e;margin-top:8px">Benchmark comparison: ARIMA ${ar.beatsNaive ? "beats" : "does not beat"} naive carry-forward and ${ar.beatsRollingMean ? "beats" : "does not beat"} rolling-mean on the holdout sample.</div>`;
  })()}

  <div class="sec-title">Trend Velocity <span class="badge-pill ${
    timelineIsLive ? "live" : "ai"
  }" style="font-size:8px">${timelineIsLive ? "LIVE Google" : "AI estimate"}</span></div>
  ${[
    ["Last Year", r.pastScore, "#d4d0c4"],
    ["This Year", r.presentScore, "#2563eb"],
    ["Next Year (Projected)", r.futureScore, "#16a34a"],
  ]
    .map(
      ([l, v, c]) =>
        `<div class="bar-row"><div class="bar-lbl"><span>${l}</span><span>${v}/100</span></div><div class="bar-track"><div class="bar-fill" style="width:${v}%;background:${c}"></div></div></div>`
    )
    .join("")}

  <div class="sec-title">Timeline <span class="badge-pill ${
    timelineIsLive ? "live" : "ai"
  }" style="font-size:8px">${timelineIsLive ? "LIVE Google" : "AI estimate"}</span></div>
  <div class="tl-grid">
    ${[
      {
        period: "Last Year",
        year: year - 1,
        summary: r.pastSummary,
        badge: r.pastTrendBadge,
      },
      {
        period: "This Year",
        year: year,
        summary: r.presentSummary,
        badge: r.presentTrendBadge,
      },
      {
        period: "Forecast",
        year: year + 1,
        summary: r.futureSummary,
        badge: r.futureTrendBadge,
        future: true,
      },
    ]
      .map(
        (tt) =>
          `<div class="tl-box${tt.future ? " future" : ""}"><div class="tl-period">${tt.period}</div><div class="tl-year">${tt.year}</div>${
            tt.badge
              ? `<div class="badge ${badgeCls(tt.badge)}">${esc(tt.badge)}</div><br>`
              : ""
          }<div class="tl-body">${esc(tt.summary || "")}</div></div>`
      )
      .join("")}
  </div>

  <div class="sec-title">Market Analysis <span class="badge-pill ai" style="font-size:8px">AI generated</span></div>
  <div class="report-body">${esc(r.marketAnalysis || r.fullReport || "")}</div>

  <div class="sec-title">Input Breakdown Analysis <span class="badge-pill ai" style="font-size:8px">AI generated</span></div>
  <div class="report-body">${esc(r.inputBreakdownAnalysis || "No input breakdown provided.")}</div>

  <div class="sec-title">Competition Analysis <span class="badge-pill ai" style="font-size:8px">AI generated</span></div>
  <div class="report-body">${esc(r.competitionAnalysis || "No competition analysis provided.")}</div>

  <div class="sec-title">Political Analysis <span class="badge-pill ai" style="font-size:8px">AI generated</span></div>
  <div class="report-body">${esc(r.politicalAnalysis || "No political analysis provided.")}</div>
  ${wtoHTML}
  ${followupHTML}

  ${
    p.currentAvgPrice
      ? `<div class="sec-title">Price History & Forecast <span class="badge-pill ${
          pricingIsLive ? "live" : "ai"
        }" style="font-size:8px">${pricingIsLive ? "LIVE eBay" : "AI estimate"}</span></div>
  <div style="font-size:10px;color:#8c897e;margin-bottom:8px">Historical window: last ${HISTORY_WEEKS} weeks</div>
  <div class="grid-4">
    <div class="stat${pricingIsLive ? " live" : ""}"><div class="stat-lbl">Avg Price Today <span class="badge-pill ${
      pricingIsLive ? "live" : "ai"
    }">${pricingIsLive ? "LIVE" : "AI"}</span></div><div class="stat-val c-blue">$${p.currentAvgPrice?.toFixed(
      2
    )}</div><div class="stat-sub">$${p.typicalPriceRangeLow}$${p.typicalPriceRangeHigh} typical${
          pricingIsLive && p.liveSampleSize ? `  ${p.liveSampleSize} listings` : ""
        }</div></div>
    <div class="stat"><div class="stat-lbl">Year-over-Year</div><div class="stat-val ${
      p.priceChangeYoY >= 0 ? "c-green" : "c-red"
    }">${p.priceChangeYoY >= 0 ? "+" : ""}${p.priceChangeYoY?.toFixed(
          1
        )}%</div><div class="stat-sub">Trend: ${esc(p.priceTrend)}</div></div>
    <div class="stat"><div class="stat-lbl">12-Month Forecast</div><div class="stat-val c-purple">$${p.forecastAvgPrice12mo?.toFixed(
      2
    )}</div><div class="stat-sub">Projected avg</div></div>
    <div class="stat"><div class="stat-lbl">24-Month Forecast</div><div class="stat-val c-purple">$${p.forecastAvgPrice24mo?.toFixed(
      2
    )}</div><div class="stat-sub">Outlook: ${esc(p.priceOutlook)}</div></div>
  </div>${sparkSVG}<div style="height:14px"></div>
  <div class="grid-2">
    <div><div class="drv-lbl bull">Price-Up Factors</div>${(p.priceBullishDrivers || [])
      .map((d) => `<div class="drv bull"><span>?</span>${esc(d)}</div>`)
      .join("")}</div>
    <div><div class="drv-lbl bear">Price-Down Factors</div>${(p.priceBearishDrivers || [])
      .map((d) => `<div class="drv bear"><span>?</span>${esc(d)}</div>`)
      .join("")}</div>
  </div>
  <div class="verdict"><div class="verdict-lbl">Verdict</div><div class="verdict-txt">${esc(
    p.pricingVerdict || ""
  )}</div></div>`
      : ""
  }

  <div class="sec-title">Keyword Signals <span class="badge-pill ai" style="font-size:8px">AI estimate</span></div>
  <div class="kw-lbl">Rising Now</div><div class="chip-group">${(r.hotKeywords || [])
    .map((k) => chip(k, "hot"))
    .join("")}</div>
  <div class="kw-lbl">Fading</div><div class="chip-group">${(r.warmKeywords || [])
    .map((k) => chip(k, "warm"))
    .join("")}</div>
  <div class="kw-lbl">Declining</div><div class="chip-group">${(r.coldKeywords || [])
    .map((k) => chip(k, "cold"))
    .join("")}</div>
  <div class="kw-lbl">Keyword Summary</div><div class="chip-group">${(r.hotKeywords || [])
    .slice(0, 3)
    .map((k) => chip(k, "hot"))
    .join("")}</div>

  <div class="sec-title">Brand Intelligence <span class="badge-pill ai" style="font-size:8px">AI estimate</span></div>
  <div class="grid-2">
    <div><div class="kw-lbl">Leading Brands</div>${(r.leadingBrands || [])
      .map((b, i) => `<div class="brand-row lead"><div class="brand-num lead">${i + 1}</div>${esc(b)}</div>`)
      .join("")}</div>
    <div><div class="kw-lbl">Rising Challengers</div>${(r.risingBrands || [])
      .map((b) => `<div class="brand-row rise"><div class="brand-num rise">?</div>${esc(b)}</div>`)
      .join("")}</div>
  </div>

  <div class="sec-title">Product Signals <span class="badge-pill ai" style="font-size:8px">AI estimate</span></div>
  <div class="kw-lbl">Trending Now</div><div class="grid-2" style="margin-bottom:10px">${(r.topProducts || [])
    .map((p2) => `<div class="prod-box"><div class="ps hot">Trending</div>${esc(p2)}</div>`)
    .join("")}</div>
  <div class="kw-lbl">Losing Steam</div><div class="grid-2">${(r.fadingProducts || [])
    .map((p2) => `<div class="prod-box fading"><div class="ps fade">Fading</div>${esc(p2)}</div>`)
    .join("")}</div>

  <div class="sec-title">Data Sources & Methodology</div>
  ${DATA_SOURCES.map(
    (src, i) =>
      `<div class="src-row"><div class="src-num">${i + 1}</div><div><div class="src-name">${esc(
        src.name
      )} <span class="badge-pill ${src.tag}">${src.tag === "live" ? "LIVE" : "AI"}</span></div><div class="src-type">${esc(
        src.type
      )}</div><div class="src-desc">${esc(src.desc)}</div></div></div>`
  ).join("")}

  <div class="disclaimer"><strong>Disclaimer:</strong> News coverage and Google Trends are fetched live (best-effort; Google Trends may be rate-limited). Pricing uses live eBay sold/completed data when available; otherwise pricing falls back to active listings or AI estimates. All other non-live scores and forecasts are AI-generated estimates, not real-time data. Always verify with primary sources before making decisions.</div>
  <div class="footer"><span>Market Intel Agent  "${esc(r.category)}" Report</span><span>${date}</span></div>
</div></body></html>`;
}



